spring:
  application:
    name: oauth
  profiles:
    active: dev
server:
  port: 8765
  servlet:
    context-path: oauth
    session:
      cookie:
        path: /
        name: _oauth_token_
        max-age: 86400


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false